<?php return '
        <h2>sed quasi quod sint velit</h2>
        <p>Voluptatem reprehenderit incidunt eaque nemo. Perspiciatis id quibusdam eum sed sunt qui. Magnam eum voluptatem non harum. Porro id et sint ad.</p>
        <img class="img-fluid" src="https://dummyimage.com/650" alt="alt anh Voluptatem reprehenderit incidunt eaque nemo. Perspiciatis id quibusdam eum sed sunt qui. Magnam eum voluptatem non harum. Porro id et sint ad.">
        <p>Id distinctio sapiente quis. Iste neque non qui ut fugiat odio exercitationem. Nam nesciunt sed officia. Mollitia architecto dolorem vitae et. Velit vero nostrum officia minima at iusto et in. Totam sed et consequatur corporis qui culpa quaerat. Expedita iste ipsum labore corporis laudantium repudiandae quidem voluptas. Enim velit iste dolores labore iure. Ipsum soluta quam autem accusamus dolores quis et. Rerum libero dolorem fuga eos sit harum dolorem. Rem et ut odio rerum. Doloremque voluptate sint inventore ut corrupti non dicta. Nam et ipsum sapiente consequatur. Minima modi sed consequatur dolor et tenetur. Consequatur blanditiis totam quaerat cupiditate ducimus. Dolor voluptatum saepe eligendi quibusdam ab dolorem aut minus. Quis cumque sapiente doloremque explicabo nostrum. Cumque voluptate autem in et consequatur voluptas. Velit temporibus quisquam nihil autem. Amet neque qui molestias nobis. Sed aut laudantium deserunt voluptates unde quisquam voluptas ullam.</p>
        
        <h2>impedit repudiandae non at excepturi</h2>
        <p>Non consequatur et quo nihil. Ab commodi fugit dicta quia similique. Autem distinctio qui minima veniam.</p>
        <img class="img-fluid" src="https://dummyimage.com/650" alt="alt anh Non consequatur et quo nihil. Ab commodi fugit dicta quia similique. Autem distinctio qui minima veniam.">
        <p>Aperiam ex velit saepe facilis repellat molestiae. Eum ut et labore ipsum quia officia. Rerum qui commodi ut natus quas numquam. Et voluptatum tenetur magni quas hic minima. Natus quos voluptates sit eius. Molestias qui ipsa facilis. Eum ullam ut enim similique velit. Fugit ratione quis tenetur voluptate quod. Fugit dolor et dolores nulla laborum animi. Velit asperiores quisquam vero aut totam ut iure. Molestiae et doloremque sunt et. Natus voluptas non iste distinctio numquam. Quis repellendus et est et. Veritatis unde ut et. Assumenda autem cumque tempora ut et deleniti facere suscipit. Aspernatur consequatur id ipsum dignissimos. Suscipit quia unde reiciendis doloribus. Aliquid cumque omnis ullam quidem. Delectus doloribus id quam consequatur sunt. Unde impedit voluptate non et perferendis distinctio accusamus qui.</p>
        
        <h2>ut porro deserunt sit at</h2>
        <p>Dolores ut voluptas hic doloremque est dolores eos. Eum dolore voluptatibus quis facilis nihil quasi nemo. Et rerum atque sapiente similique incidunt.</p>
        <img class="img-fluid" src="https://dummyimage.com/650" alt="alt anh Dolores ut voluptas hic doloremque est dolores eos. Eum dolore voluptatibus quis facilis nihil quasi nemo. Et rerum atque sapiente similique incidunt.">
        <p>Dolor libero ea alias deserunt odit aut. Exercitationem fugiat suscipit modi atque quasi unde temporibus. Nihil est ut nesciunt nesciunt eligendi maiores ipsum. Occaecati molestiae et nesciunt officiis. Dolorem nam labore corporis. Minus iure ut veritatis adipisci voluptates. Omnis suscipit sunt occaecati distinctio voluptatum totam provident. Quis dolor maiores enim libero et. Soluta harum facilis laudantium et eaque. Et et suscipit distinctio reprehenderit animi esse eligendi dignissimos. Eligendi repudiandae ducimus eaque excepturi est. Voluptas omnis et libero necessitatibus repellat culpa nihil. Quasi dolores molestiae ut.</p>
        
        <h2>omnis ratione et nobis adipisci</h2>
        <p>Est architecto cumque nihil animi facilis ab. Ea enim ut impedit sit accusamus ratione saepe. Placeat sunt autem dolorum cumque rem inventore. Quia sint est eum vel dolores.</p>
        <img class="img-fluid" src="https://dummyimage.com/650" alt="alt anh Est architecto cumque nihil animi facilis ab. Ea enim ut impedit sit accusamus ratione saepe. Placeat sunt autem dolorum cumque rem inventore. Quia sint est eum vel dolores.">
        <p>Laboriosam voluptatem expedita nihil voluptatum. Quo suscipit est repellat sed accusantium accusamus. Reiciendis doloremque quidem dicta porro blanditiis. Placeat voluptatibus ipsam minus iure inventore dolores omnis. Inventore dolorum est ipsa reprehenderit. Est alias fugit numquam doloribus. Aliquid voluptate minus fugiat omnis. Quaerat itaque quidem aut. Quo voluptatem et quas ad unde et esse. Ut eveniet minus non et sunt aut. Voluptas quod molestias ad. Eos velit et eum voluptates. Ullam laudantium ut nam itaque expedita nesciunt. Id nemo perspiciatis natus.</p>
        ';